# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New Section
"""

# Create a dictionary of codons and corresponding amino acids.
codon_dict = {
    "ATA": "I", "ATC": "I", "ATT": "I", "ATG": "M",
    "ACA": "T", "ACC": "T", "ACG": "T", "ACT": "T",
    "AAC": "N", "AAT": "N", "AAA": "K", "AAG": "K",
    "AGC": "S", "AGT": "S", "AGA": "R", "AGG": "R",
    "CTA": "L", "CTC": "L", "CTG": "L", "CTT": "L",
    "CCA": "P", "CCC": "P", "CCG": "P", "CCT": "P",
    "CAC": "H", "CAT": "H", "CAA": "Q", "CAG": "Q",
    "CGA": "R", "CGC": "R", "CGG": "R", "CGT": "R",
    "GTA": "V", "GTC": "V", "GTG": "V", "GTT": "V",
    "GCA": "A", "GCC": "A", "GCG": "A", "GCT": "A",
    "GAC": "D", "GAT": "D", "GAA": "E", "GAG": "E",
    "GGA": "G", "GGC": "G", "GGG": "G", "GGT": "G",
    "TCA": "S", "TCC": "S", "TCG": "S", "TCT": "S",
    "TTC": "F", "TTT": "F", "TTA": "L", "TTG": "L",
    "TAC": "Y", "TAT": "Y", "TAA": "Stop", "TAG": "Stop",
    "TGC": "C", "TGT": "C", "TGA": "Stop", "TGG": "W",
}

def dna_to_protein(DNAseq):
    # Clean the input: remove spaces, newlines, and convert to uppercase.
    DNAseq_valid = DNAseq.replace('\n', '').replace(' ', '').upper().strip()

    # Check and validate the sequence. It should only contain A, T, C, G
    valid_bases = {'A', 'T', 'C', 'G'}
    if not DNAseq_valid:
        print("Error: DNA sequence is empty.")
        return None
    elif any(base not in valid_bases for base in DNAseq_valid):
        print("Error: DNA sequence contains invalid characters. Only A, T, C, G are allowed.")
        return None

    # Create a storage string for a protein sequence.
    protein_seq = ""

    # Create a loop to go through DNA sequence and translate it in protein sequence one amino acid per codon.
    # If there is no codon in the end (there are less than 3 residues in the end of a DNA sequence), translation will be stopped.
    for i in range(0, len(DNAseq_valid), 3):
        codon = DNAseq_valid[i:i + 3]
        if len(codon) < 3:
            break
        # Go to the dictionary and find the suitable amino acid for the current codon in the translated DNA sequence.
        # If the Stop codon is found, the translation will end. Another check for tha valid codon (this time for its presence in the dictionary).
        if codon in codon_dict:
            amino_acid = codon_dict[codon]
            if amino_acid == "Stop":
                break
            protein_seq += amino_acid
        else:
            print(f"Warning: Codon {codon} is not valid.")
            break

    return protein_seq

# Example for DNA sequence (the beginning of the TP53 gene sequence taken from RefSeq NCBI)
DNAseq = "ctccttggtt caagtaattc tcctgcctca gactccagag tagctgggat tacaggcgcc"
protein = dna_to_protein(DNAseq)
print("Protein sequence:", protein)